name: Release versioned container image

on:
  push:
    tags:        
      - release/v*

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Version from Tag Name
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 4)
  
      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push api
        run: |
          DOCKER_BUILDKIT=1 docker build -f Dockerfile.api . -t ${{ secrets.REGISTRY_HOST }}/${{ github.event.repository.name }}/api:${{ steps.get_version.outputs.VERSION }}
          docker push ${{ secrets.REGISTRY_HOST }}/${{ github.event.repository.name }}/api:${{ steps.get_version.outputs.VERSION }}

      - name: Build and push core
        run: |
          DOCKER_BUILDKIT=1 docker build -f Dockerfile.core . -t ${{ secrets.REGISTRY_HOST }}/${{ github.event.repository.name }}/core:${{ steps.get_version.outputs.VERSION }}
          docker push ${{ secrets.REGISTRY_HOST }}/${{ github.event.repository.name }}/core:${{ steps.get_version.outputs.VERSION }}

      - name: Build and push web
        run: |
          DOCKER_BUILDKIT=1 docker build -f Dockerfile.web . -t ${{ secrets.REGISTRY_HOST }}/${{ github.event.repository.name }}/web:${{ steps.get_version.outputs.VERSION }}
          docker push ${{ secrets.REGISTRY_HOST }}/${{ github.event.repository.name }}/web:${{ steps.get_version.outputs.VERSION }}
